version: '{build}'
pull_requests:
  do_not_increment_build_number: true
build_script:
  - ps: dotnet build .\NullFight.sln -c Release; dotnet pack -c Release .\NullFight\NullFight.csproj --no-build
branches:
  only:
  - master
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
test: on
artifacts:
- path: NullFight\bin\release\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: GRi9ZCBuwCb3xcQEcHfXSklKFGxoJsmz26iAUFGI2fbvzwZpO+3TWP/5/hFsMxd0
  skip_symbols: true
  on:
    branch: master